platform :ios, '11.2'

source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

def shared
  pod 'RxEureka', :path => '../'
  pod 'RxSwift', '5.0.0'
  pod 'RxCocoa', '5.0.0'
end

def shared_tests
  pod 'Nimble', '~> 7.0'
  pod 'Quick', '~> 1.2'
end

target 'RxEureka-Example' do
  shared
end

target 'RxEureka-Tests' do
  shared
  shared_tests
end
